### ISSUE TITLE
What's the URL for this?

### ISSUE THREAD

**Issue by bkuhl** [jacksoncage/phppgadmin-docker#10]
I got this container running, but am not able to access it.

 * `http://xxxxxx:xxxxx` is showing the default apache page
 * `http://xxxxxx:xxxxx/phppgadmin` is showing a 403

What URL can I use to access phppgadmin?  According to the virtual host it looks like `/phppgadmin` should work.

**Comment by hellomedia** [comment]
Any news on this ?

**Comment by bkuhl** [comment]
The correct URL is http://xxxxxx:xxxxx/browser.  I'm glad you posted here because it reminded me to submit a PR to the readme.
